### ISSUE TITLE
NullPointer Exception in IntelliJ

### ISSUE THREAD

**Issue by yanislavm** [Hazem-Ben-Khalfallah/test-cherry#14]
It seems that some refactoring tasks in IntelliJ are causing NPEs
```
Error during processing of: ForwardingReceiverController.java
java.lang.NullPointerException
    at com.blacknebula.testcherry.refactor.ShouldReference.resolve(ShouldReference.java:85)
    at com.intellij.psi.impl.search.MethodTextOccurrenceProcessor.processReference(MethodTextOccurrenceProcessor.java:53)
    at com.intellij.psi.impl.search.MethodTextOccurrenceProcessor.processTextOccurrence(MethodTextOccurrenceProcessor.java:33)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$5.lambda$execute$0(PsiSearchHelperImpl.java:942)
    at com.intellij.psi.impl.search.LowLevelSearchUtil.processTreeUp(LowLevelSearchUtil.java:88)
    at com.intellij.psi.impl.search.LowLevelSearchUtil.lambda$processElementsAtOffsets$0(LowLevelSearchUtil.java:179)
    at com.intellij.psi.impl.search.LowLevelSearchUtil.processOffsets(LowLevelSearchUtil.java:205)
    at com.intellij.psi.impl.search.LowLevelSearchUtil.processElementsAtOffsets(LowLevelSearchUtil.java:178)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$5.execute(PsiSearchHelperImpl.java:938)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.processInReadAction(PsiSearchHelperImpl.java:272)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$2.processInReadAction(PsiSearchHelperImpl.java:263)
    at com.intellij.openapi.application.ReadActionProcessor.lambda$process$0(ReadActionProcessor.java:25)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:844)

```

**Comment by Hazem-Ben-Khalfallah** [comment]
Thank you @yanislavm for you PR!
The version 3.6 has been submitted to Jetbrains marketplace. It will be validated  within two business days.

**Comment by yanislavm** [comment]
thanks @Hazem-Ben-Khalfallah
